services:
  app:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    environment:
      - APP_ENV=local
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - type: bind
        source: .
        target: /workspace
    stdin_open: true
    tty: true
    command: /bin/bash
